export const SOUNDS = [
  "button",
  "caution",
  "celebration",
  "disabled",
  "notification",
  "progress_loop",
  "ringtone_loop",
  "select",
  "swipe",
  "swipe_01",
  "swipe_02",
  "swipe_03",
  "swipe_04",
  "swipe_05",
  "tap_01",
  "tap_02",
  "tap_03",
  "tap_04",
  "tap_05",
  "toggle_off",
  "toggle_on",
  "transition_down",
  "transition_up",
  "type_01",
  "type_02",
  "type_03",
  "type_04",
  "type_05",
] as const;

export type SoundName = (typeof SOUNDS)[number];
